simulating:
  logPercent: 0.1
  matrixLenX: 1000
  matrixLenY: 1000
  allowTimeProgressInIdle: true
  floatPrecision: 8
  graphicsToPlot:
    [
      { xAxis: "Simulation time", yAxis: "Surface coverage" },
      { xAxis: "Simulation time", yAxis: "Density F" },
      { xAxis: "Simulation time", yAxis: "Density S" },
    ]

consts:
  mass: 1
  edes: 51000
  edif: 25500
  vdes: 1e+15
  vdif: 1e+13
  er: 14000
  erlh: 0
  fDensity: 1.5e+15
  fi: 0.002
  sDensity: 3e+12
  agDensity: 1e+15
